### ISSUE TITLE
static_pe_anomaly pe checksum int cast issue?

### ISSUE THREAD

**Issue by mallorybobalice** [spender-sandbox/community-modified#105]
hi, 

anyone else seeing the following on exes:
e.g. on 4cebfbdd7756c30b54ad0ebcbafe420e 

2016-04-01 15:14:42,987 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "static_pe_anomaly":
Traceback (most recent call last):
  File "/utils/../lib/cuckoo/core/plugins.py", line 351, in process
    data = current.run()
  File "/utils/../modules/signatures/static_pe_anomaly.py", line 113, in run
    actual = int(self.results["static"]["pe"]["actual_checksum"], 16)
TypeError: int() can't convert non-string with explicit base

Not sure if the signature relies on pefile, but the latest  2016.3.28 pip version is installed
thanks. 

mb

**Comment by mallorybobalice** [comment]
aaanyone?

**Comment by KillerInstinct** [comment]
No issues here. Can you add a print statement to see what self.results["static"]["pe"]["actual_checksum"] is for that analysis?

**Comment by spender-sandbox** [comment]
Don't use the latest pefile, it's completely broken.  Take one from last year instead.

-Brad
