### ISSUE TITLE
Is there anything here that isn't in the main cuckoo/community?

### ISSUE THREAD

**Issue by blacktop** [spender-sandbox/community-modified#237]
Sorry for the question issue.

Thanks

**Comment by spender-sandbox** [comment]
Nope nothing, I just waste my time working on this one.

-Brad

**Comment by blacktop** [comment]
Wait... is that cyber-sarcasim I detect? 😏

**Comment by blacktop** [comment]
It does seem like you and @kevross33 create merge requests in both so I thought that while yours might be more current that everything would eventually make it's way to cuckoo proper?

**Comment by spender-sandbox** [comment]
I definitely have only ever contributed to this one, though it may be easy to be confused given the amount of code/ideas plagiarized from here that exist upstream.

-Brad

**Comment by blacktop** [comment]
I apologize man, I ran this query and saw your name everywhere so I wrongly assumed - https://github.com/cuckoosandbox/community/search?utf8=✓&q=Optiv

I do a lot of FOSS (not to the extent that you do though) and I know it is a mostly thankless obsession.

Keep up the awesome work!

...and **thank you** :)

**Comment by spender-sandbox** [comment]
Yes, Kevin did those which is why it contains proper copyright/attribution :)

-Brad
