### ISSUE TITLE
False Negative Dridex

### ISSUE THREAD

**Issue by kevross33** [spender-sandbox/community-modified#71]
Dridex sig does not fire on recent samples i.e MD5 58858caf4971fb89aaa7e84a385d975e

**Comment by KillerInstinct** [comment]
I noticed this too -- can you confirm if https://github.com/spender-sandbox/community-modified/commit/b326a0d45a1d5c1c69cf23efd71e29fd014080ea#diff-3be73edcae62513fa79ddf73d920582b resolves it?

**Comment by kevross33** [comment]
Hi,

Yes this resolves it against recent Dridex sample from today (010e0d1c0518844bd6624f644156d008) as just tested in my sandbox. You can get this sample I used from https://www.hybrid-analysis.com/sample/7c355f5044291eef6d39fa7b93dff6f8497d92d2072cc3813cf5313e0c6f570b?environmentId=4
